version: "3.9"
services:
  qdrant:
    image: "qdrant/qdrant"
    ports:
      - "6333:6333"
  api:
    image: "ghcr.io/codelibs/embedding-api:snapshot"
    ports:
      - "8080:8080"
    environment:
      MODEL_NAME: "paraphrase-multilingual-mpnet-base-v2"h
