version: "3.9"
services:
  qdrant_primary:
    image: "qdrant/qdrant:v1.4.1"
    ports:
      - "6333:6333"
    environment:
      QDRANT__CLUSTER__ENABLED: "true"
    command: [ "./qdrant", "--uri", "http://qdrant_primary:6335" ]
  qdrant_secondary:
    image: "qdrant/qdrant:v1.4.1"
    environment:
      QDRANT__CLUSTER__ENABLED: "true"
    command:
      [
        "./qdrant",
        "--bootstrap",
        "http://qdrant_primary:6335"
      ]
  api:
    image: "ghcr.io/codelibs/embedding-api:snapshot"
    ports:
      - "8080:8080"
    environment:
      MODEL_NAME: "paraphrase-multilingual-mpnet-base-v2"
